# Generated by Django 4.1.3 on 2022-12-05 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseball', '0007_club_team_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='email',
        ),
    ]
